services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: always
    env_file:
      - api/build.env
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
      - minio
    networks:
      - minionetwork

  resize:
    build:
      context: .
      dockerfile: resize/Dockerfile
    restart: always
    env_file:
      - resize/build.env
    depends_on:
      - rabbitmq
      - minio
    networks:
      - minionetwork

  rabbitmq:
    image: rabbitmq:3.11.2-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "pass"
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - minionetwork

  minio:
    image: quay.io/minio/minio:latest
    hostname: minioserver
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minionetwork
    volumes:
      - "minio_data:/data"
    environment:
      - MINIO_ACCESS_KEY=MINIOACCESSKEY
      - MINIO_SECRET_KEY=MINIOSECRETKEY

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
